server:
  port: 8088

spring:
  ai:
    openai:
      base-url: https://proxy.yizhan.club/
      api-key: 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
      embedding:
        options:
          model: text-davinci-003
      chat:
        #指定某一个API配置(覆盖全局配置)
        api-key: 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
        base-url: https://proxy.yizhan.club/
        options:
          model: gpt-3.5-turbo # 模型配置